<!-- pubspec.yaml -->
name: whatsapp_contact_manager
description: WhatsApp Contact Manager - Otomatik kişi ekleme uygulaması
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Kişi yönetimi için
  contacts_service: ^0.6.3
  
  # İzin yönetimi için  
  permission_handler: ^10.4.3
  
  # Uygulama açma için
  device_apps: ^2.2.0
  
  # Dosya yolu için
  path_provider: ^2.1.1
  
  # UI icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # App icon
  assets:
    - assets/images/

<!-- android/app/build.gradle için gerekli eklemeler -->
android {
    compileSdkVersion 33
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.example.whatsapp_contact_manager"
        minSdkVersion 21
        targetSdkVersion 33
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
            useProguard false
        }
    }
}
